package pomodo_timer;


import java.awt.Event.*;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew
 */
public class Pomodoro_View extends javax.swing.JFrame {

    
    
    long startValue, resumeMinutes;
    boolean showResume = true;
    boolean resumeTimer = false;
    
    public Pomodoro_View() {
        initComponents();
        resumeButton.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        startReset = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Time Elapsed:");

        jLabel2.setText("Pomodoro #:");

        jLabel3.setText("HH:MM:SS");

        jLabel4.setText("jLabel4");

        startReset.setText("Start");
        startReset.setToolTipText("");
        startReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startResetActionPerformed(evt);
            }
        });
        startReset.setBounds(30, 40, 90, 23);
        jLayeredPane2.add(startReset, javax.swing.JLayeredPane.DEFAULT_LAYER);

        exitButton.setText("Exit");
        exitButton.setToolTipText("");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        exitButton.setBounds(270, 40, 80, 23);
        jLayeredPane2.add(exitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        resumeButton.setText("Pause");
        resumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeButtonActionPerformed(evt);
            }
        });
        resumeButton.setBounds(150, 40, 90, 23);
        jLayeredPane2.add(resumeButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addContainerGap(183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // Exit when exit button has been hit
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    
    //This actionlistener checks to see if the resume button has been hit. If it has not, use System.nano time to calculate seconds.
    //If resume button has been hit, add 1.0 to the current value at which thread was paused. *kind of hack*
     ActionListener timerFunction = new ActionListener()
                         {
                           public void actionPerformed (ActionEvent e)
                           {
                                if (resumeTimer == false)
                                {
                                    System.out.println(startValue+"\n");
                                    jLabel3.setText(Double.toString(get_time(startValue)));
                                }
                                else if (resumeTimer == true)
                                {
                                    System.out.println(startValue+"\n");
                                    resumeMinutes+=1.0;
                                    jLabel3.setText(Double.toString(resumeMinutes));
                                }
                             }
                         };
    //Initiate timer with listener
    Timer t = new Timer(1000, timerFunction);
    
    //Checks to see if the timer thread is running
    // if so, it resets the value of 'startValue'
    private void startResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startResetActionPerformed

        this.set_timer();
        if ((this.t.isRunning()) == true || (this.showResume == false))
        {
            this.set_timer();
            this.resumeTimer = false;
            
        }
        this.t.start();
        resumeButton.setVisible(true);
        startReset.setText("Restart");
        
    }//GEN-LAST:event_startResetActionPerformed

    //Set booleans for action button. Pause by default.
    //If hit, button displays resume and the Timer thread stops
    //If hit again, Timer thread starts and the pause label is shown
    //          resumeTimer flag is also set to true
    private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeButtonActionPerformed
        // TODO add your handling code here:
        if (showResume == true)
        {
            resumeButton.setText("Resume");
            showResume = false;
            this.t.stop();
        }
        else
        {
            resumeButton.setText("Pause");
            showResume = true;
            resumeTimer = true;
            this.t.start();
        }
            
        
    }//GEN-LAST:event_resumeButtonActionPerformed

   public void set_timer() //assign current nanotime to long startvalue
   {
        startValue = System.nanoTime();
   }
    
   //Retrieves current time and computes seconds using System nanotime.
    public double get_time(long startValue)
    {
       long time_elapsed = System.nanoTime() - startValue;
        
       long minutes = TimeUnit.SECONDS.convert(time_elapsed, TimeUnit.NANOSECONDS);
       //System.out.println("start "+startValue);
       //System.out.println("time_elapsed "+time_elapsed);
       //System.out.println("minutes "+minutes);
        
       resumeMinutes = minutes;
       return minutes;
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pomodoro_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pomodoro_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pomodoro_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pomodoro_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Pomodoro_View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton resumeButton;
    private javax.swing.JButton startReset;
    // End of variables declaration//GEN-END:variables
}
